// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/main/proto/demo.proto

/*
Package demo is a generated protocol buffer package.

It is generated from these files:
	src/main/proto/demo.proto

It has these top-level messages:
	DemoRequest
	DemoReply
*/
package demo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
//import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DemoRequest struct {
	FirstName string `protobuf:"bytes,1,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName" json:"lastName,omitempty"`
}

func (m *DemoRequest) Reset()                    { *m = DemoRequest{} }
func (m *DemoRequest) String() string            { return proto.CompactTextString(m) }
func (*DemoRequest) ProtoMessage()               {}
func (*DemoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DemoRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *DemoRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type DemoReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *DemoReply) Reset()                    { *m = DemoReply{} }
func (m *DemoReply) String() string            { return proto.CompactTextString(m) }
func (*DemoReply) ProtoMessage()               {}
func (*DemoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DemoReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DemoRequest)(nil), "DemoRequest")
	proto.RegisterType((*DemoReply)(nil), "DemoReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Demo service

type DemoClient interface {
	SayHello(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoReply, error)
}

type demoClient struct {
	cc *grpc.ClientConn
}

func NewDemoClient(cc *grpc.ClientConn) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) SayHello(ctx context.Context, in *DemoRequest, opts ...grpc.CallOption) (*DemoReply, error) {
	out := new(DemoReply)
	err := grpc.Invoke(ctx, "/Demo/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Demo service

type DemoServer interface {
	SayHello(context.Context, *DemoRequest) (*DemoReply, error)
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Demo/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).SayHello(ctx, req.(*DemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Demo_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/main/proto/demo.proto",
}

func init() { proto.RegisterFile("src/main/proto/demo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x2e, 0x4a, 0xd6,
	0xcf, 0x4d, 0xcc, 0xcc, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0x49, 0xcd, 0xcd, 0xd7,
	0x03, 0x33, 0xa5, 0x64, 0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13,
	0xf3, 0xf2, 0xf2, 0x4b, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0x8a, 0x21, 0xb2, 0x4a, 0xee, 0x5c, 0xdc,
	0x2e, 0xa9, 0xb9, 0xf9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x32, 0x5c, 0x9c, 0x69,
	0x99, 0x45, 0xc5, 0x25, 0x7e, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08,
	0x01, 0x21, 0x29, 0x2e, 0x8e, 0x9c, 0x44, 0xa8, 0x24, 0x13, 0x58, 0x12, 0xce, 0x57, 0x52, 0xe5,
	0xe2, 0x84, 0x18, 0x54, 0x90, 0x53, 0x29, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98,
	0x0e, 0x33, 0x04, 0xc6, 0x35, 0xf2, 0xe4, 0x62, 0x01, 0x29, 0x13, 0x72, 0xe4, 0xe2, 0x08, 0x4e,
	0xac, 0xf4, 0x48, 0xcd, 0xc9, 0xc9, 0x17, 0xe2, 0xd1, 0x43, 0x72, 0x82, 0x14, 0x97, 0x1e, 0xdc,
	0x1c, 0x25, 0xe9, 0xa6, 0xcb, 0x4f, 0x26, 0x33, 0x89, 0x2a, 0x09, 0xe8, 0x97, 0x19, 0xea, 0xa7,
	0x56, 0x24, 0xe6, 0x16, 0xe4, 0xa4, 0xea, 0xa7, 0x26, 0x67, 0xe4, 0x5b, 0x31, 0x6a, 0x39, 0xc9,
	0x73, 0x09, 0x24, 0xe7, 0xe7, 0xea, 0x41, 0x85, 0xf5, 0x40, 0x5e, 0x76, 0x02, 0xbb, 0x21, 0x00,
	0xe4, 0xb3, 0x00, 0xc6, 0x24, 0x36, 0xb0, 0x17, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0xa0, 0x7e, 0xec, 0x1d, 0x01, 0x00, 0x00,
}
