// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.example.demo;

public interface DemoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();
}
