// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.example.demo;

public interface DemoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
