// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bye/bye.proto

/*
Package bye is a generated protocol buffer package.

It is generated from these files:
	bye/bye.proto

It has these top-level messages:
	ByeRequest
	ByeReply
	Image
*/
package bye

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ByeRequest struct {
	FirstName string `protobuf:"bytes,1,opt,name=firstName" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName" json:"lastName,omitempty"`
}

func (m *ByeRequest) Reset()                    { *m = ByeRequest{} }
func (m *ByeRequest) String() string            { return proto.CompactTextString(m) }
func (*ByeRequest) ProtoMessage()               {}
func (*ByeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ByeRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ByeRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type ByeReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ByeReply) Reset()                    { *m = ByeReply{} }
func (m *ByeReply) String() string            { return proto.CompactTextString(m) }
func (*ByeReply) ProtoMessage()               {}
func (*ByeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ByeReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Image struct {
	ImageId int64 `protobuf:"varint,1,opt,name=image_id,json=imageId" json:"image_id,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Image) GetImageId() int64 {
	if m != nil {
		return m.ImageId
	}
	return 0
}

func init() {
	proto.RegisterType((*ByeRequest)(nil), "bye.ByeRequest")
	proto.RegisterType((*ByeReply)(nil), "bye.ByeReply")
	proto.RegisterType((*Image)(nil), "bye.Image")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Bye service

type ByeClient interface {
	SayBye(ctx context.Context, in *ByeRequest, opts ...grpc.CallOption) (*ByeReply, error)
}

type byeClient struct {
	cc *grpc.ClientConn
}

func NewByeClient(cc *grpc.ClientConn) ByeClient {
	return &byeClient{cc}
}

func (c *byeClient) SayBye(ctx context.Context, in *ByeRequest, opts ...grpc.CallOption) (*ByeReply, error) {
	out := new(ByeReply)
	err := grpc.Invoke(ctx, "/bye.Bye/SayBye", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bye service

type ByeServer interface {
	SayBye(context.Context, *ByeRequest) (*ByeReply, error)
}

func RegisterByeServer(s *grpc.Server, srv ByeServer) {
	s.RegisterService(&_Bye_serviceDesc, srv)
}

func _Bye_SayBye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ByeServer).SayBye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bye.Bye/SayBye",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ByeServer).SayBye(ctx, req.(*ByeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bye_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bye.Bye",
	HandlerType: (*ByeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayBye",
			Handler:    _Bye_SayBye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bye/bye.proto",
}

func init() { proto.RegisterFile("bye/bye.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x50, 0xc1, 0x4a, 0x03, 0x31,
	0x14, 0x64, 0x5b, 0x6c, 0xb7, 0x0f, 0x4a, 0x25, 0x78, 0xa8, 0x4b, 0x11, 0x09, 0x1e, 0xc4, 0xc3,
	0x06, 0xf5, 0xe6, 0x71, 0x11, 0xa1, 0x08, 0x52, 0xd6, 0x0f, 0x90, 0xb7, 0xee, 0x73, 0x09, 0x24,
	0x9b, 0xd8, 0x44, 0x31, 0x57, 0x7f, 0xc1, 0x4f, 0xf3, 0x17, 0xfc, 0x10, 0x49, 0x6c, 0xdd, 0xdb,
	0x9b, 0x79, 0xc3, 0x30, 0x33, 0x30, 0x6f, 0x02, 0x89, 0x26, 0x50, 0x69, 0xb7, 0xc6, 0x1b, 0x36,
	0x6e, 0x02, 0x15, 0xab, 0xce, 0x98, 0x4e, 0x91, 0x40, 0x2b, 0x05, 0xf6, 0xbd, 0xf1, 0xe8, 0xa5,
	0xe9, 0xdd, 0x9f, 0x84, 0xdf, 0x01, 0x54, 0x81, 0x6a, 0x7a, 0x7d, 0x23, 0xe7, 0xd9, 0x0a, 0x66,
	0x2f, 0x72, 0xeb, 0xfc, 0x03, 0x6a, 0x5a, 0x66, 0xa7, 0xd9, 0xf9, 0xac, 0x1e, 0x08, 0x56, 0x40,
	0xae, 0x70, 0xf7, 0x1c, 0xa5, 0xe7, 0x3f, 0xe6, 0x67, 0x90, 0x27, 0x1f, 0xab, 0x02, 0x5b, 0xc2,
	0x54, 0x93, 0x73, 0xd8, 0xed, 0x3d, 0xf6, 0x90, 0x73, 0x38, 0x58, 0x6b, 0xec, 0x88, 0x1d, 0x43,
	0x2e, 0xe3, 0xf1, 0x24, 0xdb, 0xa4, 0x19, 0xd7, 0xd3, 0x84, 0xd7, 0xed, 0xd5, 0x3d, 0x8c, 0xab,
	0x40, 0xec, 0x16, 0x26, 0x8f, 0x18, 0xe2, 0xb5, 0x28, 0x63, 0xa3, 0x21, 0x65, 0x31, 0x1f, 0x08,
	0xab, 0x02, 0x2f, 0x3e, 0xbf, 0x7f, 0xbe, 0x46, 0x47, 0x7c, 0x21, 0xde, 0x2f, 0x05, 0x7d, 0xa0,
	0xb6, 0x2a, 0x8d, 0x70, 0x93, 0x5d, 0x54, 0x27, 0x70, 0xf8, 0x6c, 0x74, 0xb9, 0x63, 0xcb, 0x96,
	0xb4, 0xa9, 0x62, 0xd0, 0x4d, 0x2c, 0xbf, 0xc9, 0x9a, 0x49, 0x5a, 0xe1, 0xfa, 0x37, 0x00, 0x00,
	0xff, 0xff, 0xa6, 0xbb, 0x18, 0x17, 0x39, 0x01, 0x00, 0x00,
}
